language: c
before_install:
  # Install dependencies
  - sudo apt-get update
  - sudo apt-get -y install build-essential

script:
  - (mkdir cmakebuild && cd cmakebuild && cmake .. && make -j5 && cd .. && rm -rf cmakebuild)

compiler:
  - clang
  - gcc

notifications:
  webhooks: http://n.tkte.ch/h/1187/bzOwZEFZDLNMMt0CEto-XdvN
